apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels: # these labels are deployment labels
    app: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: cart
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    app: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: cart
 namespace: roboshop
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cart
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization }} # usually 75 in real environment